// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package sqlite

import ()

type Safe struct {
	ID       int64   `db:"id" json:"id"`
	Nickname string  `db:"nickname" json:"nickname"`
	Currency float64 `db:"currency" json:"currency"`
}
