name: Criando Docker Container e Enviando para o DockerHub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Git Checkout
      uses: actions/checkout@v3

    - name: Build the Docker Image    
      run: |
        export VERSION=$(sed -n 's/version = "\(.*\)"/\1/p' Cargo.toml)
        docker build -t peusgarbi/joguinho:$VERSION -t peusgarbi/joguinho:latest .

    - name: Docker Login, Push to Hub, Logout
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: |
        echo $DOCKERHUB_PASSWORD
        docker login -u $DOCKERHUB_USERNAME --password-stdin
        docker push peusgarbi/joguinho:$VERSION
        docker push peusgarbi/joguinho:latest
        docker logout