name: Criando Docker Container e Enviando para o DockerHub

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git Checkout
      uses: actions/checkout@v3

    - name: Build the Docker Image    
      run: docker build -t peusgarbi/joguinho:$IMAGE_TAG .

    - name: Docker Login, Push to Hub, Logout
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: |
        docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
        docker push peusgarbi/joguinho:$IMAGE_TAG
        docker logout